# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f3a7d1bfd694b30a036df90c7b6d1cf53310d02ade14529a7eea9c24e3e4b9e7eb92ad9f5561754c2b537687583f895dc2786d5d15e3e9ff945b43adc26177c

test:
  secret_key_base: cd556d4d1513956b0641500f6e9a217e2260be0c8a503398b8379d5bd2fddd3f3daa78431c4501f5d2fc40ae6c6c372d79e04706b08dc50acb4d42ddcba7418b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
